### ISSUE TITLE
White paper-redesign

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/boltchain.io#77]
現有白皮書風格置換為新版Boltchain設計風格

**Comment by JodieWu** [comment]
完成時間：6 hr
https://drive.google.com/file/d/1o4JYtEIontEq7xuJqirCv3mKhRhgvers/view?usp=share_link

**Comment by Luphia** [comment]
- 需優化設計
- 移除錯誤標題圖片

**Comment by JodieWu** [comment]
完成時間：4 hr
https://drive.google.com/file/d/1WcggqNUJTm_S24_8tn_0avn6BO2-7rc6/view?usp=share_link
